package errorz

var (
	ErrUnauthorizedAccess        = ErrUnauthorized.JoinError("Unauthorized access")
	ErrForbiddenAccess           = ErrForbidden.JoinError("Forbidden access")
	ErrInvalidToken              = ErrBadRequest.JoinError("Invalid token")
	ErrInvalidUUID               = ErrBadRequest.JoinError("Invalid UUID")
	ErrRecordNotFound            = ErrNotFound.JoinError("Record not found")
	ErrInvalidUserNameOrPassword = ErrBadRequest.JoinError("Invalid username and password")
	ErrEmailTaken                = ErrConflict.JoinError("Email already registered")
	ErrInvalidCredentials        = ErrUnauthorized.JoinError("Invalid email or password")
	ErrInvalidRefreshToken       = ErrUnauthorized.JoinError("Invalid or expired refresh token")
	ErrInvalidPickToken          = ErrUnauthorized.JoinError("Invalid or expired tenant selection token")
	ErrTenantNotFound            = ErrNotFound.JoinError("Tenant not found")
	ErrMembershipNotFound        = ErrForbidden.JoinError("No access to this tenant")
	ErrWeakPassword              = ErrBadRequest.JoinError("Password must be at least 8 characters")
	ErrInvalidResetToken         = ErrBadRequest.JoinError("Invalid or expired reset token")
	ErrWrongCurrentPassword      = ErrUnauthorized.JoinError("Current password is incorrect")
	ErrExtensionMismatch         = ErrBadRequest.JoinError("file extension not supported")
	ErrThumbExtensionMismatch    = ErrBadRequest.JoinError("file extension not supported for thumbnail")
	ErrFileRead                  = ErrBadRequest.JoinError("file read error")
)
